tag: ''
train_from_scratch: true
resume_from_previous_state:
  test_error:
  pre_database_dir:
  mlip_path:
  isolated_atom_energies:
generated_struct_numbers:
- 8000
- 2000
buildcell_options:
fragment_file:
fragment_numbers:
num_processes_buildcell: 128
num_of_initial_selected_structs:
- 80
- 20
num_of_rss_selected_structs: 100
initial_selection_enabled: true
rss_selection_method: bcur2i
bcur_params:
  soap_paras:
    l_max: 12
    n_max: 12
    atom_sigma: 0.0875
    cutoff: 10.5
    cutoff_transition_width: 1.0
    zeta: 4.0
    average: true
    species: true
  frac_of_bcur: 0.8
  bolt_max_num: 3000
random_seed:
include_isolated_atom: true
isolatedatom_box:
- 20.0
- 20.0
- 20.0
e0_spin: false
include_dimer: true
dimer_box:
- 20.0
- 20.0
- 20.0
dimer_range:
- 1.0
- 5.0
dimer_num: 21
custom_incar:
  ISMEAR: 0
  SIGMA: 0.05
  PREC: Accurate
  ADDGRID: .TRUE.
  EDIFF: 1e-07
  NELM: 250
  LWAVE: .FALSE.
  LCHARG: .FALSE.
  ALGO: Normal
  AMIX:
  LREAL: .FALSE.
  ISYM: 0
  ENCUT: 520.0
  KSPACING: 0.2
  GGA:
  KPAR: 8
  NCORE: 16
  LSCALAPACK: .FALSE.
  LPLANE: .FALSE.
custom_potcar:
vasp_ref_file: vasp_ref.extxyz
config_types:
- initial
- traj_early
- traj
rss_group:
- traj
test_ratio: 0.1
regularization: true
retain_existing_sigma: false
scheme: linear-hull
reg_minmax:
- - 0.1
  - 1
- - 0.001
  - 0.1
- - 0.0316
  - 0.316
- - 0.0632
  - 0.632
distillation: false
force_max:
force_label:
pre_database_dir:
mlip_type: GAP
ref_energy_name: REF_energy
ref_force_name: REF_forces
ref_virial_name: REF_virial
auto_delta: true
num_processes_fit: 32
device_for_fitting: cpu
scalar_pressure_method: uniform
scalar_exp_pressure: 1
scalar_pressure_exponential_width: 0.2
scalar_pressure_low: 0
scalar_pressure_high: 25
max_steps: 300
force_tol: 0.01
stress_tol: 0.01
stop_criterion: 0.01
max_iteration_number: 25
num_groups: 6
initial_kt: 0.3
current_iter_index: 1
hookean_repul: false
hookean_paras:
keep_symmetry: false
write_traj: true
num_processes_rss: 128
device_for_rss: cpu
mlip_hypers:
  GAP:
    general:
      at_file: train.extxyz
      default_sigma: '{0.0001 0.05 0.05 0}'
      energy_parameter_name: REF_energy
      force_parameter_name: REF_forces
      virial_parameter_name: REF_virial
      sparse_jitter: 1e-08
      do_copy_at_file: F
      openmp_chunk_size: 10000
      gp_file: gap_file.xml
      e0_offset: 0.0
      two_body: true
      three_body: false
      soap: true
    twob:
      distance_Nb_order: 2
      f0: 0.0
      add_species: T
      cutoff: 5.0
      n_sparse: 15
      covariance_type: ard_se
      delta: 2.0
      theta_uniform: 0.5
      sparse_method: uniform
      compact_clusters: T
    threeb:
      distance_Nb_order: 3
      f0: 0.0
      add_species: T
      cutoff: 3.25
      n_sparse: 100
      covariance_type: ard_se
      delta: 2.0
      theta_uniform: 1.0
      sparse_method: uniform
      compact_clusters: T
    soap:
      add_species: T
      l_max: 10
      n_max: 12
      atom_sigma: 0.5
      zeta: 4
      cutoff: 5.0
      cutoff_transition_width: 1.0
      central_weight: 1.0
      n_sparse: 6000
      delta: 1.0
      f0: 0.0
      covariance_type: dot_product
      sparse_method: cur_points
